name: Build/release

on:
  push:
    paths:
      - '.github/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            args: "-c electron-builder.yml -m"
          - os: ubuntu-latest
            args: "-c electron-builder.yml -l"
          - os: windows-latest
            args: "-c electron-builder.yml -w"

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16.17.1

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          skip_build: true
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          args: ${{ matrix.os.args }}

      - name: ls -la
        run: ls -la
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      - name: ls -la
        run: ls -la dist
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'

      - name: ls -la
        run: dir
        if: matrix.os == 'windows-latest'
      - name: ls -la
        run: dir dist
        if: matrix.os == 'windows-latest'
#      - name: Install Snapcraft
#        uses: samuelmeuli/action-snapcraft@v3
